# SPDX-FileCopyrightText: 2022 Google Inc
# SPDX-FileCopyrightText: 2022 Vladimir Rusinov <vrusinov@google.com>
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "flow001"
version = "1.0.0"
authors = ["Vladimir Rusinov <vladimir.rusinov@gmail.com>"]
edition = "2018"

[dependencies]
